export const allowedRolesByMenu = {
    all: [
        "Assistante de direction",
        "Designer",
        "Call Center",
        "Digital Manager",
        "Chef d'Agence",
        "Responsable Département Communication",
        "Responsable Corporate",
        "Communication",
        "Communicatrice",
        "Responsable Marketing et Commercial",
        "Chef Département Marketing et Commerce",
        "Responsable Juridique, Contentieux et RH",
        "RH",
        "Responsable Département Technique",
        "Chef de Service Topograqhique",
        "Chef de Service BTP",
        "Commerciale",
        "Customer Experience Manager",
        "Développeur Web",
        "Chargée Commerciale",
        "Contrôleur et Chef des Operations",
        "Géomètre",
        "Assistante géomètre",
        "Assistante Juriste",
        "Assistante Comptable",
        "Architecte",
        "Stagiaire",
        "Responsable Département Comptabilité et Finance",
        "Consultant",
        "Chauffeur",
        "DG",
        "PDG",
        "Chef d'agence",
        "Responsable Produit",
        "Responsable Commerciale",
        "Responsable commerciale",
    ],

    allAcces: ["DG", "PDG", "Consultant", "Développeur Web", "Chef d'agence"],
    kpiAcces: ["DG", "PDG", "Consultant", "Développeur Web", "Chef d'agence",
        "Responsable Département Comptabilité et Finance",
        "Responsable Département Communication",
        "Chef Département Marketing et Commerce",
        "Responsable Marketing et Commercial",
        "Responsable Département Comptabilité et Finance",
        "Responsable Département Technique",
        "Responsable Juridique, Contentieux et RH"
    ],
    corporate: [
        "DG",
        "PDG",
        "Consultant",
        "Développeur Web",
        "Chef d'agence",
        "Customer Experience Management",
        "Responsable Commerciale",
        "Responsable Marketing et Commercial",
        "Chef Département Marketing et Commerce",
    ],
    topographique: [
        "Géomètre",
        "Assistante géomètre",
        "Chef de Service Topograqhique",
        "Responsable Département Technique",
        "Chef d'agence",
        "Responsable Produit",
    ],
};
